# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='botresponse',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AlterField(
            model_name='botresponse',
            name='response',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
