# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20161212_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botresponse',
            name='response',
            field=models.CharField(max_length=1000),
        ),
    ]
