# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20161212_0619'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botresponse',
            unique_together=set([('command', 'bot')]),
        ),
    ]
