# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20161212_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botresponse',
            name='command',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='botresponse',
            unique_together=set([]),
        ),
    ]
