# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20161212_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=1000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Bot')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
